## Imports

In [1]:
import pyreadr
import pandas as pd

## The Data

In [2]:
path = './data/'

train_normal_path = 'TEP_FaultFree_Training.RData'
train_faulty_path = 'TEP_Faulty_Training.RData'

test_normal_path = 'TEP_FaultFree_Testing.RData'
test_faulty_path = 'TEP_Faulty_Testing.RData'

train_normal_complete = pyreadr.read_r(path + train_normal_path)['fault_free_training']
train_faulty_complete = pyreadr.read_r(path + train_faulty_path)['faulty_training']

test_normal_complete = pyreadr.read_r(path + test_normal_path)['fault_free_testing']
test_faulty_complete = pyreadr.read_r(path + test_faulty_path)['faulty_testing']

In [3]:
type(train_normal_complete)

pandas.core.frame.DataFrame

### Features shape

In [4]:
print('train_normal_complete shape: ',train_normal_complete.shape)
print('train_faulty_complete shape: ',train_faulty_complete.shape)
print('\n')
print('test_normal_complete shape: ',test_normal_complete.shape)
print('test_faulty_complete shape: ',test_faulty_complete.shape)

train_normal_complete shape:  (250000, 55)
train_faulty_complete shape:  (5000000, 55)


test_normal_complete shape:  (480000, 55)
test_faulty_complete shape:  (9600000, 55)

### How the data look like
**Train Normal Complete**

In [5]:
train_normal_complete.head()
# ilham please find the information about some columns
# - faultNumber
# - simulationRun
# - sample
# and find it each 4 datasets 

# faultNumber = 0 means that there is normal and not faulty
# simulation = 1..2...
# samples = 1~500

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
0,0.0,1.0,1,0.25038,3674.0,4529.0,9.2320,26.889,42.402,2704.3,...,53.744,24.657,62.544,22.137,39.935,42.323,47.757,47.510,41.258,18.447
1,0.0,1.0,2,0.25109,3659.4,4556.6,9.4264,26.721,42.576,2705.0,...,53.414,24.588,59.259,22.084,40.176,38.554,43.692,47.427,41.359,17.194
2,0.0,1.0,3,0.25038,3660.3,4477.8,9.4426,26.875,42.070,2706.2,...,54.357,24.666,61.275,22.380,40.244,38.990,46.699,47.468,41.199,20.530
3,0.0,1.0,4,0.24977,3661.3,4512.1,9.4776,26.758,42.063,2707.2,...,53.946,24.725,59.856,22.277,40.257,38.072,47.541,47.658,41.643,18.089
4,0.0,1.0,5,0.29405,3679.0,4497.0,9.3381,26.889,42.650,2705.1,...,53.658,28.797,60.717,21.947,39.144,41.955,47.645,47.346,41.507,18.461

In [6]:
train_normal_complete['faultNumber'].value_counts()

0.0    250000
Name: faultNumber, dtype: int64

In [10]:
# train_normal_complete['simulationRun'].value_counts()
# 500

In [12]:
# train_normal_complete['sample'].value_counts()
# 500

**Test Normal Complete**

In [13]:
test_normal_complete.head()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
0,0,1.0,1,0.25171,3672.4,4466.3,9.5122,27.057,42.473,2705.6,...,54.494,24.527,59.710,22.357,40.149,40.074,47.955,47.300,42.100,15.345
1,0,1.0,2,0.25234,3642.2,4568.7,9.4145,26.999,42.586,2705.2,...,53.269,24.465,60.466,22.413,39.956,36.651,45.038,47.502,40.553,16.063
2,0,1.0,3,0.24840,3643.1,4507.5,9.2901,26.927,42.278,2703.5,...,54.000,24.860,60.642,22.199,40.074,41.868,44.553,47.479,41.341,20.452
3,0,1.0,4,0.25153,3628.3,4519.3,9.3347,26.999,42.330,2703.9,...,53.860,24.553,61.908,21.981,40.141,40.066,48.048,47.440,40.780,17.123
4,0,1.0,5,0.21763,3655.8,4571.0,9.3087,26.901,42.402,2707.7,...,53.307,21.775,61.891,22.412,37.696,38.295,44.678,47.530,41.089,18.681

In [14]:
test_normal_complete['faultNumber'].value_counts()

0    480000
Name: faultNumber, dtype: int64

In [20]:
# test_normal_complete['simulationRun'].value_counts()
# 960

In [21]:
# test_normal_complete['sample'].value_counts()
# 500

**Train Faulty Complete**

In [7]:
train_faulty_complete.head()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
0,1,1.0,1,0.25038,3674.0,4529.0,9.2320,26.889,42.402,2704.3,...,53.744,24.657,62.544,22.137,39.935,42.323,47.757,47.510,41.258,18.447
1,1,1.0,2,0.25109,3659.4,4556.6,9.4264,26.721,42.576,2705.0,...,53.414,24.588,59.259,22.084,40.176,38.554,43.692,47.427,41.359,17.194
2,1,1.0,3,0.25038,3660.3,4477.8,9.4426,26.875,42.070,2706.2,...,54.357,24.666,61.275,22.380,40.244,38.990,46.699,47.468,41.199,20.530
3,1,1.0,4,0.24977,3661.3,4512.1,9.4776,26.758,42.063,2707.2,...,53.946,24.725,59.856,22.277,40.257,38.072,47.541,47.658,41.643,18.089
4,1,1.0,5,0.29405,3679.0,4497.0,9.3381,26.889,42.650,2705.1,...,53.658,28.797,60.717,21.947,39.144,41.955,47.645,47.346,41.507,18.461

In [23]:
# train_faulty_complete['faultNumber'].value_counts()
# in train faulty there 20 faultNumber
# and each faultnumber there 250.000

In [30]:
# train_faulty_complete['simulationRun'].value_counts()
# in the train faulty simulation there 1~343

In [32]:
# train_faulty_complete['sample'].value_counts()
# the train faulty sample has value 1~500
# and each sample has 10.000

**Test Faulty Complete**

In [33]:
test_faulty_complete.head()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
0,1,1.0,1,0.25171,3672.4,4466.3,9.5122,27.057,42.473,2705.6,...,54.494,24.527,59.710,22.357,40.149,40.074,47.955,47.300,42.100,15.345
1,1,1.0,2,0.25234,3642.2,4568.7,9.4145,26.999,42.586,2705.2,...,53.269,24.465,60.466,22.413,39.956,36.651,45.038,47.502,40.553,16.063
2,1,1.0,3,0.24840,3643.1,4507.5,9.2901,26.927,42.278,2703.5,...,54.000,24.860,60.642,22.199,40.074,41.868,44.553,47.479,41.341,20.452
3,1,1.0,4,0.25153,3628.3,4519.3,9.3347,26.999,42.330,2703.9,...,53.860,24.553,61.908,21.981,40.141,40.066,48.048,47.440,40.780,17.123
4,1,1.0,5,0.21763,3655.8,4571.0,9.3087,26.901,42.402,2707.7,...,53.307,21.775,61.891,22.412,37.696,38.295,44.678,47.530,41.089,18.681

In [35]:
# test_faulty_complete['faultNumber'].value_counts()
# there 1~20 and each has 480.000

In [37]:
# test_faulty_complete['simulationRun'].value_counts()
# there 1~343 and each has 19200

In [39]:
# test_faulty_complete['sample'].value_counts()
# in the sampel there 960 and each 10.00

### Features Names
**Train Normal Complete**

In [40]:
train_normal_complete.columns

Index(['faultNumber', 'simulationRun', 'sample', 'xmeas_1', 'xmeas_2',
       'xmeas_3', 'xmeas_4', 'xmeas_5', 'xmeas_6', 'xmeas_7', 'xmeas_8',
       'xmeas_9', 'xmeas_10', 'xmeas_11', 'xmeas_12', 'xmeas_13', 'xmeas_14',
       'xmeas_15', 'xmeas_16', 'xmeas_17', 'xmeas_18', 'xmeas_19', 'xmeas_20',
       'xmeas_21', 'xmeas_22', 'xmeas_23', 'xmeas_24', 'xmeas_25', 'xmeas_26',
       'xmeas_27', 'xmeas_28', 'xmeas_29', 'xmeas_30', 'xmeas_31', 'xmeas_32',
       'xmeas_33', 'xmeas_34', 'xmeas_35', 'xmeas_36', 'xmeas_37', 'xmeas_38',
       'xmeas_39', 'xmeas_40', 'xmeas_41', 'xmv_1', 'xmv_2', 'xmv_3', 'xmv_4',
       'xmv_5', 'xmv_6', 'xmv_7', 'xmv_8', 'xmv_9', 'xmv_10', 'xmv_11'],
      dtype='object')

**Train Faulty Complete**

In [41]:
train_faulty_complete.columns

Index(['faultNumber', 'simulationRun', 'sample', 'xmeas_1', 'xmeas_2',
       'xmeas_3', 'xmeas_4', 'xmeas_5', 'xmeas_6', 'xmeas_7', 'xmeas_8',
       'xmeas_9', 'xmeas_10', 'xmeas_11', 'xmeas_12', 'xmeas_13', 'xmeas_14',
       'xmeas_15', 'xmeas_16', 'xmeas_17', 'xmeas_18', 'xmeas_19', 'xmeas_20',
       'xmeas_21', 'xmeas_22', 'xmeas_23', 'xmeas_24', 'xmeas_25', 'xmeas_26',
       'xmeas_27', 'xmeas_28', 'xmeas_29', 'xmeas_30', 'xmeas_31', 'xmeas_32',
       'xmeas_33', 'xmeas_34', 'xmeas_35', 'xmeas_36', 'xmeas_37', 'xmeas_38',
       'xmeas_39', 'xmeas_40', 'xmeas_41', 'xmv_1', 'xmv_2', 'xmv_3', 'xmv_4',
       'xmv_5', 'xmv_6', 'xmv_7', 'xmv_8', 'xmv_9', 'xmv_10', 'xmv_11'],
      dtype='object')

**Test Normal Complete**

In [42]:
test_normal_complete.columns

Index(['faultNumber', 'simulationRun', 'sample', 'xmeas_1', 'xmeas_2',
       'xmeas_3', 'xmeas_4', 'xmeas_5', 'xmeas_6', 'xmeas_7', 'xmeas_8',
       'xmeas_9', 'xmeas_10', 'xmeas_11', 'xmeas_12', 'xmeas_13', 'xmeas_14',
       'xmeas_15', 'xmeas_16', 'xmeas_17', 'xmeas_18', 'xmeas_19', 'xmeas_20',
       'xmeas_21', 'xmeas_22', 'xmeas_23', 'xmeas_24', 'xmeas_25', 'xmeas_26',
       'xmeas_27', 'xmeas_28', 'xmeas_29', 'xmeas_30', 'xmeas_31', 'xmeas_32',
       'xmeas_33', 'xmeas_34', 'xmeas_35', 'xmeas_36', 'xmeas_37', 'xmeas_38',
       'xmeas_39', 'xmeas_40', 'xmeas_41', 'xmv_1', 'xmv_2', 'xmv_3', 'xmv_4',
       'xmv_5', 'xmv_6', 'xmv_7', 'xmv_8', 'xmv_9', 'xmv_10', 'xmv_11'],
      dtype='object')

**Test Faulty Complete**

In [43]:
test_faulty_complete.columns

Index(['faultNumber', 'simulationRun', 'sample', 'xmeas_1', 'xmeas_2',
       'xmeas_3', 'xmeas_4', 'xmeas_5', 'xmeas_6', 'xmeas_7', 'xmeas_8',
       'xmeas_9', 'xmeas_10', 'xmeas_11', 'xmeas_12', 'xmeas_13', 'xmeas_14',
       'xmeas_15', 'xmeas_16', 'xmeas_17', 'xmeas_18', 'xmeas_19', 'xmeas_20',
       'xmeas_21', 'xmeas_22', 'xmeas_23', 'xmeas_24', 'xmeas_25', 'xmeas_26',
       'xmeas_27', 'xmeas_28', 'xmeas_29', 'xmeas_30', 'xmeas_31', 'xmeas_32',
       'xmeas_33', 'xmeas_34', 'xmeas_35', 'xmeas_36', 'xmeas_37', 'xmeas_38',
       'xmeas_39', 'xmeas_40', 'xmeas_41', 'xmv_1', 'xmv_2', 'xmv_3', 'xmv_4',
       'xmv_5', 'xmv_6', 'xmv_7', 'xmv_8', 'xmv_9', 'xmv_10', 'xmv_11'],
      dtype='object')

### Statistical Describe
**Train Normal Complete**

In [44]:
train_normal_complete.describe()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
count,250000.0,250000.000000,250000.000000,250000.000000,250000.000000,250000.00000,250000.000000,250000.000000,250000.000000,250000.000000,...,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,0.0,250.500000,250.500000,0.250482,3663.785706,4508.81979,9.347101,26.902196,42.337598,2705.037865,...,53.973668,24.639472,61.298501,22.216644,40.055456,38.098898,46.534295,47.958591,41.104304,18.118706
std,0.0,144.337567,144.337567,0.030873,34.006357,39.21542,0.085721,0.211485,0.218513,7.525596,...,0.469663,3.037743,1.243805,0.530156,1.526751,2.965266,2.351304,2.716520,0.540817,1.463678
min,0.0,1.000000,1.000000,0.122450,3511.800000,4336.90000,8.972700,25.951000,41.394000,2672.300000,...,52.095000,11.977000,55.961000,19.749000,33.389000,25.959000,36.937000,36.641000,38.586000,11.705000
25%,0.0,125.750000,125.750000,0.229770,3640.800000,4482.40000,9.289300,26.758000,42.188000,2700.100000,...,53.657000,22.602000,60.453000,21.864000,39.021000,36.081000,44.931000,46.265000,40.740000,17.130000
50%,0.0,250.500000,250.500000,0.250510,3663.700000,4508.80000,9.347100,26.902000,42.338000,2705.000000,...,53.974000,24.644000,61.298000,22.217000,40.058000,38.091000,46.530000,47.820000,41.104000,18.119000
75%,0.0,375.250000,375.250000,0.271200,3686.800000,4535.30000,9.405100,27.046000,42.487000,2710.000000,...,54.290000,26.674000,62.144000,22.568000,41.084000,40.117000,48.140000,49.651000,41.470000,19.111000
max,0.0,500.000000,500.000000,0.391740,3808.400000,4683.70000,9.729800,27.818000,43.257000,2739.100000,...,56.118000,38.351000,66.443000,24.525000,47.498000,50.729000,56.443000,59.616000,43.930000,24.762000

**Train Faulty Complete**

In [14]:
train_faulty_complete.describe()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
count,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,...,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06
mean,1.050000e+01,2.505000e+02,2.505000e+02,2.613588e-01,3.663777e+03,4.506046e+03,9.370345e+00,2.690156e+01,4.236419e+01,2.723005e+03,...,5.431755e+01,3.043177e+01,6.324830e+01,2.295485e+01,3.992297e+01,3.807265e+01,4.643742e+01,5.060598e+01,4.194845e+01,1.884376e+01
std,5.766282e+00,1.443373e+02,1.443373e+02,1.495384e-01,4.316941e+01,1.110368e+02,3.646151e-01,2.320034e-01,3.172128e-01,7.599384e+01,...,5.258092e+00,2.048365e+01,7.400080e+00,1.108258e+01,1.293348e+01,2.949138e+00,2.358468e+00,1.759840e+01,1.001227e+01,5.176705e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,-4.735000e-03,3.327400e+03,3.540700e+03,6.639900e+00,2.538600e+01,3.965600e+01,2.413800e+03,...,3.118400e+01,-2.718600e-01,-4.893100e-03,-9.941000e-02,0.000000e+00,2.280100e+01,3.492300e+01,-3.635500e-01,-2.809500e-01,-5.327000e-03
25%,5.750000e+00,1.257500e+02,1.257500e+02,2.183000e-01,3.636500e+03,4.469000e+03,9.264200e+00,2.676000e+01,4.218100e+01,2.697600e+03,...,5.349700e+01,2.228000e+01,6.031400e+01,2.142300e+01,3.831300e+01,3.604900e+01,4.487800e+01,4.547900e+01,4.057500e+01,1.714300e+01
50%,1.050000e+01,2.505000e+02,2.505000e+02,2.511300e-01,3.663300e+03,4.508500e+03,9.355200e+00,2.690100e+01,4.234800e+01,2.705600e+03,...,5.397000e+01,2.521500e+01,6.149900e+01,2.212900e+01,3.996700e+01,3.815000e+01,4.633900e+01,4.806500e+01,4.120600e+01,1.829500e+01
75%,1.525000e+01,3.752500e+02,3.752500e+02,2.832100e-01,3.690200e+03,4.548000e+03,9.456800e+00,2.704300e+01,4.252400e+01,2.715000e+03,...,5.444300e+01,2.879700e+01,6.284100e+01,2.273800e+01,4.150700e+01,3.999100e+01,4.803100e+01,5.188700e+01,4.194900e+01,1.953700e+01
max,2.000000e+01,5.000000e+02,5.000000e+02,1.017500e+00,3.906700e+03,5.175800e+03,1.224000e+01,2.848600e+01,4.465300e+01,3.000500e+03,...,1.000000e+02,1.001900e+02,1.000200e+02,1.001100e+02,9.752800e+01,5.312100e+01,5.998000e+01,1.005200e+02,1.003200e+02,1.000100e+02

**Test Normal Complete**

In [15]:
test_normal_complete.describe()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
count,480000.0,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,...,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000
mean,0.0,250.500000,480.500000,0.250526,3663.764171,4508.898696,9.346866,26.902165,42.337820,2705.013416,...,53.974160,24.643706,61.295689,22.212485,40.057926,38.098705,46.534148,47.975245,41.103468,18.122284
std,0.0,144.337429,277.128268,0.031273,33.943033,39.398350,0.086148,0.211148,0.218114,7.578226,...,0.470525,3.076030,1.246459,0.536269,1.532972,2.966680,2.348197,2.815153,0.542646,1.464914
min,0.0,1.000000,1.000000,0.122610,3503.300000,4338.200000,8.936300,26.018000,41.441000,2667.800000,...,51.818000,11.985000,55.762000,19.847000,32.596000,24.594000,36.354000,35.587000,38.557000,10.856000
25%,0.0,125.750000,240.750000,0.229390,3640.800000,4482.300000,9.288800,26.759000,42.190000,2699.900000,...,53.656000,22.564000,60.449000,21.855000,39.025000,36.078000,44.934000,46.136000,40.738000,17.131000
50%,0.0,250.500000,480.500000,0.250520,3663.800000,4508.900000,9.346900,26.902000,42.338000,2704.900000,...,53.974000,24.646000,61.297000,22.210000,40.059000,38.103000,46.536000,47.858000,41.103000,18.122000
75%,0.0,375.250000,720.250000,0.271600,3686.800000,4535.500000,9.405100,27.045000,42.486000,2710.000000,...,54.292000,26.716000,62.142000,22.568000,41.094000,40.120000,48.137000,49.808000,41.469000,19.113000
max,0.0,500.000000,960.000000,0.390320,3824.700000,4689.200000,9.748900,27.822000,43.250000,2736.900000,...,56.103000,38.449000,66.494000,24.654000,46.758000,50.631000,56.357000,60.160000,43.601000,24.524000

**Test Faulty Complete**

In [16]:
test_faulty_complete.describe()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
count,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,...,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06
mean,1.050000e+01,2.505000e+02,4.805000e+02,2.565512e-01,3.665140e+03,4.510175e+03,9.389582e+00,2.690135e+01,4.237570e+01,2.725131e+03,...,5.473719e+01,2.935285e+01,6.373647e+01,2.328299e+01,3.925227e+01,3.804629e+01,4.642267e+01,4.964156e+01,4.203599e+01,1.940324e+01
std,5.766282e+00,1.443373e+02,2.771280e+02,1.413868e-01,4.337049e+01,1.083498e+02,3.811052e-01,2.274992e-01,3.221519e-01,7.920024e+01,...,7.637258e+00,1.947320e+01,8.876150e+00,1.276332e+01,1.318921e+01,2.937202e+00,2.341916e+00,1.751728e+01,1.187598e+01,8.885751e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,-4.985500e-03,3.308400e+03,3.557100e+03,6.695700e+00,2.534800e+01,3.967900e+01,2.420200e+03,...,7.348400e+00,-3.586600e-01,-5.222600e-03,-1.068800e-01,0.000000e+00,2.228800e+01,3.336900e+01,-6.834200e-01,-5.156500e-01,-6.774200e-03
25%,5.750000e+00,1.257500e+02,2.407500e+02,2.191700e-01,3.637600e+03,4.472900e+03,9.272700e+00,2.676300e+01,4.219000e+01,2.698300e+03,...,5.354500e+01,2.220600e+01,6.035700e+01,2.153300e+01,3.835700e+01,3.600000e+01,4.485600e+01,4.538500e+01,4.061600e+01,1.711400e+01
50%,1.050000e+01,2.505000e+02,4.805000e+02,2.504100e-01,3.664000e+03,4.509400e+03,9.356400e+00,2.690000e+01,4.235100e+01,2.705400e+03,...,5.398200e+01,2.505300e+01,6.149700e+01,2.213900e+01,3.992600e+01,3.811200e+01,4.631900e+01,4.804900e+01,4.119100e+01,1.826100e+01
75%,1.525000e+01,3.752500e+02,7.202500e+02,2.801300e-01,3.690800e+03,4.547200e+03,9.450600e+00,2.704000e+01,4.252600e+01,2.713800e+03,...,5.443300e+01,2.824100e+01,6.279000e+01,2.268700e+01,4.136500e+01,3.996100e+01,4.800800e+01,5.144600e+01,4.185300e+01,1.949000e+01
max,2.000000e+01,5.000000e+02,9.600000e+02,1.016800e+00,3.891700e+03,5.164300e+03,1.223600e+01,2.856500e+01,4.455000e+01,3.000500e+03,...,1.000000e+02,1.002100e+02,1.000200e+02,1.000900e+02,9.724500e+01,5.423000e+01,6.021600e+01,1.005800e+02,1.006100e+02,1.000100e+02

### checking the missing values

In [17]:
trncp = train_normal_complete.isnull().sum()
cnt = 0
for i in trncp:
    if i == 1:
        cnt+=1
print(cnt)

0

In [18]:
trfcp = train_faulty_complete.isnull().sum()
cnt = 0
for i in trfcp:
    if i == 1:
        cnt+=1
print(cnt)

0

In [19]:
tsncp = test_normal_complete.isnull().sum()
cnt = 0
for i in trncp:
    if i == 1:
        cnt+=1
print(cnt)

0

In [20]:
tsfcp = test_faulty_complete.isnull().sum()
cnt = 0
for i in trncp:
    if i == 1:
        cnt+=1
print(cnt)

0

we can see that there is no missing value on the dataset

### See the data types
**Train Normal Complete**

In [21]:
train_normal_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 55 columns):
faultNumber      250000 non-null float64
simulationRun    250000 non-null float64
sample           250000 non-null int32
xmeas_1          250000 non-null float64
xmeas_2          250000 non-null float64
xmeas_3          250000 non-null float64
xmeas_4          250000 non-null float64
xmeas_5          250000 non-null float64
xmeas_6          250000 non-null float64
xmeas_7          250000 non-null float64
xmeas_8          250000 non-null float64
xmeas_9          250000 non-null float64
xmeas_10         250000 non-null float64
xmeas_11         250000 non-null float64
xmeas_12         250000 non-null float64
xmeas_13         250000 non-null float64
xmeas_14         250000 non-null float64
xmeas_15         250000 non-null float64
xmeas_16         250000 non-null float64
xmeas_17         250000 non-null float64
xmeas_18         250000 non-null float64
xmeas_19         250000 non-null float64
xmeas_20         250000 non-null float64
xmeas_21         250000 non-null float64
xmeas_22         250000 non-null float64
xmeas_23         250000 non-null float64
xmeas_24         250000 non-null float64
xmeas_25         250000 non-null float64
xmeas_26         250000 non-null float64
xmeas_27         250000 non-null float64
xmeas_28         250000 non-null float64
xmeas_29         250000 non-null float64
xmeas_30         250000 non-null float64
xmeas_31         250000 non-null float64
xmeas_32         250000 non-null float64
xmeas_33         250000 non-null float64
xmeas_34         250000 non-null float64
xmeas_35         250000 non-null float64
xmeas_36         250000 non-null float64
xmeas_37         250000 non-null float64
xmeas_38         250000 non-null float64
xmeas_39         250000 non-null float64
xmeas_40         250000 non-null float64
xmeas_41         250000 non-null float64
xmv_1            250000 non-null float64
xmv_2            250000 non-null float64
xmv_3            250000 non-null float64
xmv_4            250000 non-null float64
xmv_5            250000 non-null float64
xmv_6            250000 non-null float64
xmv_7            250000 non-null float64
xmv_8            250000 non-null float64
xmv_9            250000 non-null float64
xmv_10           250000 non-null float64
xmv_11           250000 non-null float64
dtypes: float64(54), int32(1)
memory usage: 104.0 MB

**Train Faulty Complete**

In [22]:
train_faulty_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 55 columns):
faultNumber      int32
simulationRun    float64
sample           int32
xmeas_1          float64
xmeas_2          float64
xmeas_3          float64
xmeas_4          float64
xmeas_5          float64
xmeas_6          float64
xmeas_7          float64
xmeas_8          float64
xmeas_9          float64
xmeas_10         float64
xmeas_11         float64
xmeas_12         float64
xmeas_13         float64
xmeas_14         float64
xmeas_15         float64
xmeas_16         float64
xmeas_17         float64
xmeas_18         float64
xmeas_19         float64
xmeas_20         float64
xmeas_21         float64
xmeas_22         float64
xmeas_23         float64
xmeas_24         float64
xmeas_25         float64
xmeas_26         float64
xmeas_27         float64
xmeas_28         float64
xmeas_29         float64
xmeas_30         float64
xmeas_31         float64
xmeas_32         float64
xmeas_33         float64
xmeas_34         float64
xmeas_35         float64
xmeas_36         float64
xmeas_37         float64
xmeas_38         float64
xmeas_39         float64
xmeas_40         float64
xmeas_41         float64
xmv_1            float64
xmv_2            float64
xmv_3            float64
xmv_4            float64
xmv_5            float64
xmv_6            float64
xmv_7            float64
xmv_8            float64
xmv_9            float64
xmv_10           float64
xmv_11           float64
dtypes: float64(53), int32(2)
memory usage: 2.0 GB

**Test Normal Complete**

In [23]:
test_normal_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480000 entries, 0 to 479999
Data columns (total 55 columns):
faultNumber      480000 non-null int32
simulationRun    480000 non-null float64
sample           480000 non-null int32
xmeas_1          480000 non-null float64
xmeas_2          480000 non-null float64
xmeas_3          480000 non-null float64
xmeas_4          480000 non-null float64
xmeas_5          480000 non-null float64
xmeas_6          480000 non-null float64
xmeas_7          480000 non-null float64
xmeas_8          480000 non-null float64
xmeas_9          480000 non-null float64
xmeas_10         480000 non-null float64
xmeas_11         480000 non-null float64
xmeas_12         480000 non-null float64
xmeas_13         480000 non-null float64
xmeas_14         480000 non-null float64
xmeas_15         480000 non-null float64
xmeas_16         480000 non-null float64
xmeas_17         480000 non-null float64
xmeas_18         480000 non-null float64
xmeas_19         480000 non-null float64
xmeas_20         480000 non-null float64
xmeas_21         480000 non-null float64
xmeas_22         480000 non-null float64
xmeas_23         480000 non-null float64
xmeas_24         480000 non-null float64
xmeas_25         480000 non-null float64
xmeas_26         480000 non-null float64
xmeas_27         480000 non-null float64
xmeas_28         480000 non-null float64
xmeas_29         480000 non-null float64
xmeas_30         480000 non-null float64
xmeas_31         480000 non-null float64
xmeas_32         480000 non-null float64
xmeas_33         480000 non-null float64
xmeas_34         480000 non-null float64
xmeas_35         480000 non-null float64
xmeas_36         480000 non-null float64
xmeas_37         480000 non-null float64
xmeas_38         480000 non-null float64
xmeas_39         480000 non-null float64
xmeas_40         480000 non-null float64
xmeas_41         480000 non-null float64
xmv_1            480000 non-null float64
xmv_2            480000 non-null float64
xmv_3            480000 non-null float64
xmv_4            480000 non-null float64
xmv_5            480000 non-null float64
xmv_6            480000 non-null float64
xmv_7            480000 non-null float64
xmv_8            480000 non-null float64
xmv_9            480000 non-null float64
xmv_10           480000 non-null float64
xmv_11           480000 non-null float64
dtypes: float64(53), int32(2)
memory usage: 197.8 MB

**Test Faulty Complete**

In [24]:
test_faulty_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9600000 entries, 0 to 9599999
Data columns (total 55 columns):
faultNumber      int32
simulationRun    float64
sample           int32
xmeas_1          float64
xmeas_2          float64
xmeas_3          float64
xmeas_4          float64
xmeas_5          float64
xmeas_6          float64
xmeas_7          float64
xmeas_8          float64
xmeas_9          float64
xmeas_10         float64
xmeas_11         float64
xmeas_12         float64
xmeas_13         float64
xmeas_14         float64
xmeas_15         float64
xmeas_16         float64
xmeas_17         float64
xmeas_18         float64
xmeas_19         float64
xmeas_20         float64
xmeas_21         float64
xmeas_22         float64
xmeas_23         float64
xmeas_24         float64
xmeas_25         float64
xmeas_26         float64
xmeas_27         float64
xmeas_28         float64
xmeas_29         float64
xmeas_30         float64
xmeas_31         float64
xmeas_32         float64
xmeas_33         float64
xmeas_34         float64
xmeas_35         float64
xmeas_36         float64
xmeas_37         float64
xmeas_38         float64
xmeas_39         float64
xmeas_40         float64
xmeas_41         float64
xmv_1            float64
xmv_2            float64
xmv_3            float64
xmv_4            float64
xmv_5            float64
xmv_6            float64
xmv_7            float64
xmv_8            float64
xmv_9            float64
xmv_10           float64
xmv_11           float64
dtypes: float64(53), int32(2)
memory usage: 3.9 GB