In [1]:
import pyreadr
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
path = './data/'

train_normal_path = 'TEP_FaultFree_Training.RData'
train_faulty_path = 'TEP_Faulty_Training.RData'

# test_normal_path = 'TEP_FaultFree_Testing.RData'
# test_faulty_path = 'TEP_Faulty_Testing.RData'

train_normal_complete = pyreadr.read_r(path + train_normal_path)['fault_free_training']
train_faulty_complete = pyreadr.read_r(path + train_faulty_path)['faulty_training']

# test_normal_complete = pyreadr.read_r(path + test_normal_path)['fault_free_testing']
# test_faulty_complete = pyreadr.read_r(path + test_faulty_path)['faulty_testing']

In [8]:
train_normal_complete.head()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
0,0.0,1.0,1,0.25038,3674.0,4529.0,9.2320,26.889,42.402,2704.3,...,53.744,24.657,62.544,22.137,39.935,42.323,47.757,47.510,41.258,18.447
1,0.0,1.0,2,0.25109,3659.4,4556.6,9.4264,26.721,42.576,2705.0,...,53.414,24.588,59.259,22.084,40.176,38.554,43.692,47.427,41.359,17.194
2,0.0,1.0,3,0.25038,3660.3,4477.8,9.4426,26.875,42.070,2706.2,...,54.357,24.666,61.275,22.380,40.244,38.990,46.699,47.468,41.199,20.530
3,0.0,1.0,4,0.24977,3661.3,4512.1,9.4776,26.758,42.063,2707.2,...,53.946,24.725,59.856,22.277,40.257,38.072,47.541,47.658,41.643,18.089
4,0.0,1.0,5,0.29405,3679.0,4497.0,9.3381,26.889,42.650,2705.1,...,53.658,28.797,60.717,21.947,39.144,41.955,47.645,47.346,41.507,18.461

In [9]:
train_faulty_complete.head()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
0,1,1.0,1,0.25038,3674.0,4529.0,9.2320,26.889,42.402,2704.3,...,53.744,24.657,62.544,22.137,39.935,42.323,47.757,47.510,41.258,18.447
1,1,1.0,2,0.25109,3659.4,4556.6,9.4264,26.721,42.576,2705.0,...,53.414,24.588,59.259,22.084,40.176,38.554,43.692,47.427,41.359,17.194
2,1,1.0,3,0.25038,3660.3,4477.8,9.4426,26.875,42.070,2706.2,...,54.357,24.666,61.275,22.380,40.244,38.990,46.699,47.468,41.199,20.530
3,1,1.0,4,0.24977,3661.3,4512.1,9.4776,26.758,42.063,2707.2,...,53.946,24.725,59.856,22.277,40.257,38.072,47.541,47.658,41.643,18.089
4,1,1.0,5,0.29405,3679.0,4497.0,9.3381,26.889,42.650,2705.1,...,53.658,28.797,60.717,21.947,39.144,41.955,47.645,47.346,41.507,18.461

In [11]:
cols = train_normal_complete.columns[3:55]

In [15]:
# cols

In [17]:
n_prob_features = len(cols)

In [6]:
from sklearn.preprocessing import MinMaxScaler

### Train normal

In [7]:
scaler = MinMaxScaler()

In [63]:
data = pd.DataFrame(scaler.fit_transform(X = train_normal_complete[(train_normal_complete.faultNumber == 0) & (train_normal_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.475455,0.523545,0.484252,0.496565,0.509471,0.506657,0.490172,0.483362,0.529642,0.473183,...,0.466924,0.480118,0.509257,0.516536,0.472463,0.483312,0.511119,0.481638,0.471319,0.478722
variance,0.114972,0.117146,0.117945,0.114773,0.113308,0.117368,0.113015,0.111506,0.112460,0.114341,...,0.116710,0.115498,0.118562,0.111041,0.108233,0.125519,0.125329,0.122042,0.101071,0.114822

### Train Faulty

In [62]:
train_faulty_complete.faultNumber.value_counts().index
# from the result we can see that there is 20 different
# faulty type

Int64Index([20, 19, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            1],
           dtype='int64')

In [41]:
# IDV 1
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 1) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.680747,0.500849,0.501459,0.548355,0.508912,0.490065,0.372495,0.504687,0.499941,0.504185,...,0.513960,0.679713,0.508735,0.463179,0.498315,0.481409,0.496769,0.386152,0.492432,0.474835
variance,0.174527,0.113365,0.122547,0.153856,0.112852,0.114099,0.161318,0.127491,0.100474,0.119555,...,0.124692,0.174845,0.124893,0.145309,0.122364,0.121821,0.123596,0.241598,0.116913,0.110175

In [42]:
# IDV 2
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 2) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.524938,0.539477,0.586323,0.567615,0.509475,0.522741,0.381073,0.517898,0.530039,0.706364,...,0.584429,0.526394,0.529088,0.446941,0.705816,0.486907,0.513312,0.374403,0.487384,0.478802
variance,0.115587,0.109855,0.131329,0.124729,0.113364,0.121129,0.170005,0.113320,0.112980,0.210955,...,0.137222,0.114711,0.117294,0.135720,0.212051,0.125697,0.124662,0.233649,0.101691,0.115102

In [43]:
# IDV 3
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 3) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.474994,0.523528,0.485352,0.496197,0.509473,0.505882,0.490862,0.482972,0.529712,0.474299,...,0.466856,0.479941,0.510317,0.517145,0.473565,0.483268,0.511223,0.481923,0.471980,0.478709
variance,0.114972,0.117151,0.118235,0.114807,0.113308,0.117061,0.113591,0.112043,0.112436,0.114217,...,0.116717,0.115440,0.118306,0.111538,0.108128,0.125530,0.125276,0.122002,0.101164,0.114822

In [44]:
# IDV 4
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 4) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.475078,0.523541,0.484112,0.496367,0.509731,0.506917,0.490181,0.484184,0.299999,0.473042,...,0.466930,0.479807,0.509542,0.516769,0.472319,0.483354,0.511092,0.480258,0.593705,0.478764
variance,0.114920,0.117143,0.117914,0.114705,0.113247,0.117309,0.113024,0.111510,0.065990,0.114357,...,0.116713,0.115436,0.118541,0.111170,0.108237,0.125508,0.125321,0.122409,0.096018,0.114811

In [45]:
# IDV 5
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 5) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.483474,0.556086,0.522616,0.48488,0.509744,0.534649,0.485080,0.521961,0.500175,0.565101,...,0.547082,0.484846,0.496803,0.455651,0.538180,0.486156,0.521602,0.495636,0.551851,0.536809
variance,0.125491,0.107313,0.110070,0.12861,0.113484,0.119035,0.126947,0.115798,0.109893,0.116545,...,0.115519,0.124587,0.112126,0.135306,0.115208,0.124527,0.123651,0.125187,0.106983,0.108789

In [46]:
# IDV 6
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 6) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.041868,0.465242,0.390239,0.605146,0.473240,0.542422,0.840696,0.350478,0.510865,0.261451,...,0.701873,0.945790,0.519305,0.292913,0.286354,0.519311,0.496519,0.822876,0.501693,0.273441
variance,0.141666,0.108823,0.171020,0.118547,0.073104,0.076118,0.292878,0.107779,0.110072,0.194177,...,0.175775,0.188925,0.327927,0.378244,0.302643,0.069808,0.069523,0.337569,0.368380,0.175030

In [47]:
# IDV 7
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 7) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.399962,0.484565,0.459826,0.517095,0.509434,0.491596,0.441428,0.531561,0.480179,0.559316,...,0.464247,0.400655,0.610230,0.451671,0.535024,0.508313,0.522015,0.465443,0.532583,0.476150
variance,0.167653,0.109226,0.140119,0.138332,0.113471,0.105607,0.143792,0.135246,0.090718,0.126328,...,0.136889,0.168398,0.132166,0.162367,0.126966,0.122309,0.124041,0.175184,0.126377,0.115945

In [48]:
# IDV 8
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 8) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.266158,0.481645,0.515940,0.508022,0.509737,0.494795,0.437249,0.486450,0.476386,0.497211,...,0.490947,0.266485,0.517046,0.405039,0.484318,0.487998,0.498325,0.510561,0.549560,0.507250
variance,0.186247,0.109509,0.098319,0.119062,0.113082,0.102113,0.114780,0.108112,0.109409,0.118211,...,0.102127,0.186087,0.114017,0.092894,0.114313,0.126131,0.125479,0.184865,0.095266,0.115996

In [49]:
# IDV 9
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 9) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.476663,0.523743,0.494294,0.496139,0.509208,0.514798,0.489006,0.501343,0.500226,0.475938,...,0.475510,0.485898,0.508979,0.530963,0.461542,0.483690,0.510791,0.474896,0.454628,0.479020
variance,0.114845,0.116535,0.115375,0.114712,0.113368,0.116247,0.111016,0.110828,0.106969,0.112961,...,0.116243,0.115277,0.121120,0.110760,0.109767,0.125564,0.125210,0.120684,0.103877,0.114727

In [50]:
# IDV 10
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 10) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.491848,0.515479,0.460434,0.495495,0.509208,0.515447,0.470704,0.462723,0.529611,0.493578,...,0.498905,0.494675,0.479235,0.501401,0.472186,0.483656,0.512294,0.445317,0.51799,0.477003
variance,0.116749,0.119820,0.111489,0.107459,0.113376,0.118390,0.126864,0.108434,0.113302,0.115977,...,0.121136,0.116123,0.108611,0.115505,0.116417,0.125515,0.125101,0.119655,0.10612,0.114370

In [51]:
# IDV 11
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 11) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.474186,0.515650,0.479476,0.497344,0.509188,0.509143,0.499925,0.482978,0.486871,0.481300,...,0.470501,0.476248,0.510200,0.522921,0.477801,0.481078,0.510095,0.476579,0.511814,0.483237
variance,0.113692,0.117925,0.117032,0.114894,0.113129,0.118361,0.111308,0.111390,0.106229,0.115768,...,0.116953,0.114769,0.119139,0.107720,0.110495,0.125074,0.125276,0.123297,0.169959,0.116189

In [52]:
# IDV 12
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 12) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.298264,0.510777,0.558171,0.487641,0.519468,0.512856,0.438979,0.474588,0.524361,0.543731,...,0.171321,0.29708,0.614566,0.230094,0.663996,0.490477,0.497286,0.530498,0.413892,0.246187
variance,0.172235,0.119454,0.134867,0.120506,0.114048,0.109356,0.159228,0.117349,0.104428,0.128534,...,0.110105,0.17163,0.053365,0.085864,0.133682,0.120619,0.118558,0.189442,0.068631,0.044929

In [53]:
# IDV 13
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 13) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.356265,0.528878,0.527163,0.514017,0.506237,0.522746,0.460533,0.492498,0.428611,0.476573,...,0.14314,0.354225,0.353883,0.225057,0.576575,0.486561,0.509034,0.576125,0.522714,0.303120
variance,0.134288,0.114978,0.111659,0.108742,0.112263,0.101085,0.162668,0.102611,0.078672,0.122668,...,0.04557,0.134352,0.041778,0.045372,0.112653,0.124015,0.125090,0.315034,0.024059,0.036829

In [54]:
# IDV 14
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 14) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.475461,0.523148,0.484215,0.498322,0.516260,0.474153,0.481676,0.491088,0.489133,0.471288,...,0.46673,0.480257,0.514331,0.512223,0.470652,0.482946,0.510946,0.480947,0.494724,0.478586
variance,0.114943,0.117025,0.118016,0.116340,0.111135,0.119142,0.111719,0.113128,0.273003,0.114124,...,0.11677,0.115445,0.117707,0.108496,0.108059,0.126124,0.125303,0.121904,0.272880,0.115013

In [55]:
# IDV 15
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 15) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.475691,0.518147,0.490152,0.494798,0.509978,0.510510,0.506897,0.479048,0.500165,0.476400,...,0.489481,0.483058,0.509537,0.541695,0.477205,0.482243,0.514638,0.493626,0.477593,0.480547
variance,0.114968,0.116915,0.117767,0.114393,0.112958,0.115611,0.107943,0.108861,0.106970,0.114316,...,0.119082,0.114884,0.118360,0.105500,0.108472,0.126385,0.125416,0.118810,0.100021,0.115893

In [56]:
# IDV 16
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 16) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.492170,0.513065,0.502294,0.509699,0.509188,0.497966,0.446279,0.450946,0.529582,0.497532,...,0.487368,0.490847,0.503777,0.493861,0.493772,0.483534,0.512296,0.500826,0.463286,0.479957
variance,0.117613,0.119177,0.114485,0.115070,0.113128,0.118570,0.109495,0.107034,0.112978,0.116871,...,0.113952,0.115650,0.115196,0.114894,0.118854,0.124968,0.124295,0.117080,0.098161,0.115695

In [57]:
# IDV 17
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 17) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.534627,0.542433,0.490583,0.489919,0.519697,0.491379,0.485191,0.484217,0.567248,0.498787,...,0.483425,0.540314,0.511031,0.488824,0.491896,0.506824,0.502967,0.489331,0.385579,0.530043
variance,0.107585,0.097934,0.115076,0.117692,0.118042,0.117860,0.124500,0.117627,0.120549,0.119712,...,0.111984,0.107167,0.115174,0.114728,0.117503,0.122886,0.117357,0.112352,0.157305,0.111158

In [58]:
# IDV 18
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 18) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.209658,0.635374,0.635792,0.577433,0.440248,0.604157,0.652591,0.467981,0.479714,0.485897,...,0.386017,0.207882,0.646056,0.318369,0.436365,0.479185,0.438703,0.391061,0.424946,0.207259
variance,0.205132,0.138584,0.150964,0.189144,0.092895,0.151386,0.264502,0.146207,0.073117,0.131141,...,0.321063,0.205958,0.193886,0.280485,0.283161,0.098359,0.107718,0.293962,0.205746,0.086008

In [59]:
# IDV 19
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 19) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.483523,0.521801,0.481430,0.493803,0.489387,0.495290,0.490443,0.476705,0.545624,0.473850,...,0.462848,0.489040,0.506510,0.498009,0.473573,0.482635,0.507732,0.484071,0.515715,0.483522
variance,0.115802,0.118188,0.117498,0.112923,0.166474,0.123752,0.110973,0.112220,0.116500,0.114654,...,0.115836,0.116167,0.117837,0.125385,0.108814,0.125553,0.125688,0.124831,0.111478,0.113804

In [60]:
# IDV 20
data = pd.DataFrame(scaler.fit_transform(X = train_faulty_complete[(train_faulty_complete.faultNumber == 20) & (train_faulty_complete.simulationRun.isin(range(400)))].loc[:,cols]))

means = data.mean()
variances = data.std()

model_prob = pd.DataFrame(index = cols, data = {'mean': means.values, 'variance': variances.values})
model_prob.head(n_prob_features).T

,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,xmeas_8,xmeas_9,xmeas_10,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
mean,0.515911,0.534149,0.481272,0.537752,0.487114,0.427001,0.544510,0.486449,0.550094,0.489404,...,0.489895,0.517143,0.492789,0.659156,0.480051,0.506421,0.514978,0.479798,0.566538,0.510767
variance,0.109910,0.111421,0.110526,0.106625,0.116467,0.106656,0.113516,0.112581,0.103867,0.116481,...,0.115585,0.110598,0.124803,0.186676,0.115707,0.120098,0.124848,0.121039,0.109930,0.114908